@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

@baseURL= comments
@currentId = 2c2cc019-2661-410a-a79c-b1c2b3c6487d



GET http://{{host}}/{{baseURL}}/

###

GET http://{{host}}/{{baseURL}}/id/{{currentId}}

###

POST http://{{host}}/{{baseURL}}/ HTTP/1.1
Content-Type: {{contentType}}

// first ticket id : d1731e0e-e2de-44dd-b103-a2f61f993b0d
// second ticket id : 4cfd226f-252a-490f-bb72-9ba6baa42c09
// blumenfeld's id: 0488b2fb-38d9-4c26-8fda-23e0a91b18ac
# {
#   "id": "2c2cc019-2661-410a-a79c-b1c2b3c6487d",
#   "message":"I need this to be done by tommorow",
#   "sender":"0488b2fb-38d9-4c26-8fda-23e0a91b18ac",
#   "ticket":"d1731e0e-e2de-44dd-b103-a2f61f993b0d"
# }
{
  "id": "aa6e728e-0ddd-4d13-b286-cb448b85f5a6",
  "message":"Good work!",
  "sender":"0488b2fb-38d9-4c26-8fda-23e0a91b18ac",
  "ticket":"d1731e0e-e2de-44dd-b103-a2f61f993b0d"
}

###

PATCH http://{{host}}/{{baseURL}}/{{currentId}} HTTP/1.1
Content-Type: {{contentType}}




###

DELETE http://{{host}}/{{baseURL}}/{{currentId}} HTTP/1.1

###
